on:
  push:
    tags: [ '*' ]
jobs:
  publish:
    strategy:
      matrix:
        include:
          - os: ubuntu
            rid: linux-x64
          - os: windows
            rid: win-x64
            ext: .exe
          - os: macos
            rid: osx-x64
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    - run: dotnet publish -o bin/pub -r ${{ matrix.rid }}
    - uses: svenstaro/upload-release-action@v2
      # Github->Settings->Actions->General->Workflow permissions->Read and write permissions 로 설정해야 작동함.
      with:
        file: bin/pub/HexRR${{ matrix.ext }}
        asset_name: HexRR-${{ matrix.rid }}${{ matrix.ext }}
        overwrite: true
        tag: ${{ github.ref }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
